name: sr
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=19.1.7
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.2
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.6
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.12.7
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyzmq=26.2.1
  - readline=8.2
  - setuptools=75.5.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - audioread==3.0.1
      - black==24.10.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - decorator==5.1.1
      - distro==1.9.0
      - dotenv==0.9.9
      - elevenlabs==1.56.0
      - ffmpeg==1.4
      - ffmpeg-python==0.2.0
      - fonttools==4.56.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-cloud-speech==2.31.0
      - google-cloud-texttospeech==2.25.0
      - googleapis-common-protos==1.68.0
      - grpcio==1.71.0rc2
      - grpcio-status==1.71.0rc2
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - idna==3.10
      - ipdb==0.13.13
      - ipython==8.30.0
      - isort==5.13.2
      - jinja2==3.1.4
      - jiter==0.7.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.15.0
      - numba==0.61.0
      - numpy==2.1.3
      - omegaconf==2.3.0
      - openai==1.54.4
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.0.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - proto-plus==1.26.0
      - protobuf==5.29.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.2.1
      - pysrt==1.1.2
      - python-dotenv==1.0.1
      - pytube==15.0.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.21.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - streamlit==1.40.2
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tqdm==4.67.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - websockets==15.0
      - yt-dlp==2025.2.19
