[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "gtts-445018"
private_key_id = "dfc46cc0a4bb82033631bf9200cf070c92f95e4d"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCe+9azq2RSrPwf
MxEcrPkH91MeeU4H+41VWL0fiJiqaMiqu+R75aj+OMv7e7YPrlKyxmLEn+YVZr9h
CrLN8bf/syuNl7xHCBqpHx+Vtu9CUD7ypPWy4JryuazAM2UkwKodX9xAaKaYqe2G
sNmi3ejYRx8ksuC2y/jZwIvMH6B7sk8k/JPOigXNnYvGX/jQJxIsjODAlptNYcQN
SMsoHyE90Kbg4PTYWSYCdJxl5hFVF/xR0FJWEnjh4ukUauAs7Hlmky4KRiC2PtHB
cMVqLuqzf2o+SkZ/CHKIIAI58wVdtGNCHuUuN+Z50sN7IDjgi7cHNPejOsFYWAT9
iLtkP4erAgMBAAECggEACpLDb0AhYe9erSyD/NPzAa/DwNI6ME5K0pMeQx3C0FTN
+EF2KzPVfIdh50Sf2s37KXEsNZAHG0yxws4noPfaK2wmNjp/vZ9VyN2fmiEadHEl
zEurrvGJrtgFQFHz28xzTQKIgWXPx77Z9gwY8eBB/zlrq2MmssGKAU8VxjOQ1sSA
JG0aEfBxsOmBJ5ZtmiW0UhcE1L9W6a7uTdotyj37Ox8G+CuGVPAV5KzIfwyo29Z6
IrQF7VfY9/a7xfGuH8GRFAcy44/piMnrONAQ/VKpkj+s53/3+uzmaC7nxOiwnZdU
JTvn5ZPu1dz9DtbcBg/5HNaInbGTe2/5TdYL73/8YQKBgQDa0ZejQv1FSf24WIGE
OZVLoiMhgFQQrbYRISKVDZuzII2K4moP0Sq8d+F8gj1JUutHeStXdA/5q+LFResh
uh3PJAWV841D6lrDF7KNpxtFKhYy0uPAM7dDkn51S9cl0IbjsMzdfhSf5v0TF+tv
jI3gYSwme6226d9Y9YIlFd4KYwKBgQC5/3s/GtDbFVV/SlEi+uVNdVL4krr8Eqp5
gDu+/4aMgfxR9bE7FuGFgTiniwTu6X6ifDhVePAeqXUJo2Lb8x5+1jaHXQXKg4/H
0cZeT6h2NciEcbWYbsZbUPIFIRjqAa1nmrcJstUzgU77KKCSqtXdAuxjSks9L5+c
kfCRC/KsGQKBgAec0xGy+uy2LkWDjr3y4ubGtUItHL+Xy4W9CV72IjyRHVt/lQEH
3dzAru+N+GPcpqLN7FwWhZfCCxmh3RRHTVIvhqI43ulF9fJjmKqk7aXyWONbwuCk
6/NF3XBnOwztvEOfmwD5qe4GMze+1UoEMctklgygsOJ0MHj/0Y9Iu3jRAoGBALYl
j9i4thgWyGejq9mJws0cPGjZqOv6i5/5CIl/S5CGK0dISIwJWEmZxpWs+uPNHgqZ
g8GQcfZVFRyfOM0VRaQIu9XML0Onm0KgGJd7gwpgmUG66Y+hy/bZSmnjg7aGdf6j
8OQ6kbeixmoH21hGnLGXj0+dDhmZbcGy2dfxz3DhAoGBAL4r1nKYPzEjRydmGtfv
u6PumYIM0ko+0JMiIsBtHS7Zq3mlMlssM/yBVoY6zAloLwh1f+vqUTzAeFBkJgNF
9L8AqgVkW0/kZS2A0fCa3wr7zWpbhb+3/idLuy16S9CsSnTRVvxuZzlT+lmE1u2d
kVelutRQ5K/iGOw3xU7RSPpr
-----END PRIVATE KEY-----
"""
client_email = "deployment@gtts-445018.iam.gserviceaccount.com"
client_id = "108198960453363208825"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/deployment%40gtts-445018.iam.gserviceaccount.com"
universe_domain = "googleapis.com"